const ampularium = [
  {
    id: 1,
    nazov: "Anopyrin",
    skupina: "Skupina: NSAID, antiagrans",
    MU: "MU: neselektívna inhibícia COX",
    indikacie: "Indikacie: AKS",
    davkovanie: "Dávkovanie: 150 – 300 mg ",
    sposobPodania: "Spôsob podania: p.o., i.v",
    nastupAodoznenieUcinku:
      "Nástup a odoznenie účinku: po podaní sa metabolizuje na aktívny metabolit kys. salicylovú, nástup po p.o. podaní cca 20 min, biologický polčas cca 2 hod",
    NU: "NÚ: po jednorazovom podaní vzácne",
    KI: "KI: detský vek, gravidita, krvácavé stavy, peptický vred, poruchy hemokoagulácie, závažné ochorenie pečene a obličiek, asthma bronchiale, alergia na NSAID",
  },
  {
    id: 2,
    nazov: "Adenozín (Adenocor)",
    skupina:
      "Skupina: antiarytmikum, je však telu vlastná látka (metabolit ATP)",
    MU: "MÚ: viaže sa na adenozínové receptory buniek. Klinický účinok:Relaxácia hladkého svalstva (vazodilatácia), Negatívne chronotropný a dromotropný účinok (liečba SVT), Blokáda uvoľňovania noradrenalínu zo sympatikových nervových zakončení",
    indikacie: "Indikacie: liečba paroxyzmálnych SVT (úzkokomplexových)",
    davkovanie: "Dávkovanie: 6-6-12 mg i.v.",
    sposobPodania: "Spôsob podania: i.v. bolus",
    nastupAodoznenieUcinku:
      "Nástup a trvanie účinku: do 2 min, biologický polčas 10 s.",
    NU: "NÚ: hypotenzia, AV blokáda, bradykardia, začervenanie tváre, bolesti hlavy, poruchy zraku. Nežiaduce účinky rýchlo vymiznú vďaka krátkodobému účinku adenozínu    ",
    KI: "KI: AV blokáda 2. a 3. stupňa, závažné pľúcne ochorenie, hypotenzia len relatívne. Interakcie: metylxantíny (kofeín, aminofylín) znižujú účinok",
  },
  {
    id: 3,
    nazov: "Adrenalín, epinefrín (Adrenalin)",
    skupina:
      "Skupina: endogénny katecholamín, priame sympatikomimetikum alfa aj beta",
    MU: "Účinky: Vazokonstrikcia v koži a obličkách, Vazodilatácia kostrové svaly, Bronchodilatácia, Pozitívny chrono, batmo, dromo, a inotropný účinok – tonizácia myokardu. Metabolické: glykogenolýza v pečeni – hyperglykémia, lipolýza v tukovom tkanive. Endokrinné: zníženie sekrécie inzulínu. Stimulácia dýchania, bdelosti, celková psyhcostimulácia. Inhibícia alebo potenciácia uvoľnovania niektorých transmitterov",
    indikacie:
      "Použitie v UM: Základný liek pri KPR (1 mg á 4 min). Liek prvej voľby pri anafylaxii (0,5 mg i.m. á 15 min). Farmakologická stimulácia srdca pri závažných bradyarytmiách (10 mcg/min i.v.). Podpora obehu pri iných šokových stavoch (začať napr,  kontinuálne 1 mg/hod i.v.). Závažný bronchospazmus (refraktérny status asthmaticus): 50mcg i.v. á 5 min, možno aj nebulizovať Edém laryngu (laryngitída, epiglotititída)  (nebulizovať 5 mg do 5 ml F1/1)",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku:
      "Krátky biologický polčas 1 – 2 min. Preto opakované, resp. kontinuálne podávanie. Metabolizuje sa COMT (pečeň) a MAO (tkanivá). Prechádza placentárnou bariérou, ale nie HEB. Vylučuje sa močom vo forme neaktívnych metabolitov (napr. kys. vanilmandľová)",
    NU: "NÚ: tachykardia, arytmia, VT/VF, hypertenzia, krvácanie do mozgu, úzkosť, nepokoj, tras, bolesť hlavy, točenie hlavy, panika, samovražedné sklony",
    KI: "Kontraindikácie: pri život ohrozujúcich indikáciách neexistujú. Interakcie: pozor na inaktiváciu pri súčasnom podaní s NaHCO3, účinok zvyšujú – sympatikomimetiká, TAD, antihistaminiká, digoxín, účinok znižujú – fenotiazíny, námeľové alkaloidy,sympatikolytiká",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
  {
    id: 3,
    nazov: "",
    skupina: "",
    MU: "",
    indikacie: "",
    davkovanie: "",
    sposobPodania: "",
    nastupAodoznenieUcinku: "",
    NU: "",
    KI: "",
  },
];

export default ampularium;
